# Generated by Django 5.2.4 on 2025-07-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Descrição'
            ),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
    ]
