# Generated by Django 5.2.4 on 2025-07-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=250)),
                ('page_count', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                (
                    'author',
                    models.ManyToManyField(
                        related_name='books', to='authors.author'
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='books',
                        to='categories.category',
                    ),
                ),
            ],
        ),
    ]
