# Generated by Django 5.2.4 on 2025-07-29 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('page_count', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('author', models.ManyToManyField(related_name='books', to='authors.author', verbose_name='Autor(es)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
