# Generated by Django 5.2.4 on 2025-07-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'authors',
            '0002_alter_author_options_alter_author_description_and_more',
        ),
        ('books', '0001_initial'),
        (
            'categories',
            '0002_alter_category_options_alter_category_description_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(
                related_name='books',
                to='authors.author',
                verbose_name='Autor(es)',
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='books',
                to='categories.category',
                verbose_name='Categoria',
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(
                max_length=17, unique=True, verbose_name='ISBN'
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(
                verbose_name='Número de Páginas'
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Quantidade'
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
