# Generated by Django 5.2.4 on 2025-07-29 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Número inválido. Formato esperado: +5511999998888 ou 11999999999.', regex='^(\\+55)?\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Leitor',
                'verbose_name_plural': 'Leitores',
            },
        ),
    ]
