# Generated by Django 5.2.4 on 2025-07-29 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('patrons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('due_date', models.DateTimeField(verbose_name='Data prevista para devolução')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Devolvido?')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da devolução')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='Livro')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='patrons.patron', verbose_name='Emprestado para')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
