# Generated by Django 5.2.4 on 2025-07-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_author_and_more'),
        ('loans', '0001_initial'),
        ('patrons', '0002_alter_patron_options_alter_patron_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='loans',
                to='books.book',
                verbose_name='Livro',
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(
                verbose_name='Data prevista para devolução'
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_returned',
            field=models.BooleanField(
                default=False, verbose_name='Devolvido?'
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Data do Empréstimo'
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='notes',
            field=models.TextField(
                blank=True, null=True, verbose_name='Observações'
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='patron',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='loans',
                to='patrons.patron',
                verbose_name='Emprestado para',
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Data da devolução'
            ),
        ),
    ]
