# Generated by Django 5.2.4 on 2025-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_options_alter_loan_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data prevista para devolução',
            ),
        ),
    ]
