# Generated by Django 5.2.4 on 2025-07-16 22:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 15, 0, 0),
                verbose_name='Data prevista para devolução',
            ),
            preserve_default=False,
        ),
    ]
